import { z } from "zod";

export const propertySchema = z.object({
  title: z.string().min(5, "Title must be at least 5 characters"),
  propertyType: z.enum([
    "HOSTEL",
    "BEDSITTER",
    "SINGLE_ROOM",
    "APARTMENT",
    "SHARED_APARTMENT",
    "RENTAL_HOUSE",
  ]),
  description: z.string().min(30, "Description must be at least 30 characters"),
  location: z.string().min(3),
  latitude: z.number().optional().nullable(),
  longitude: z.number().optional().nullable(),
  monthlyRent: z.number().int().positive(),
  depositAmount: z.number().int().min(0).default(0),
  furnished: z.boolean().default(false),
  genderSpecific: z.string().optional().nullable(),
  amenities: z.array(z.string()).default([]),
  availability: z.enum(["AVAILABLE", "OCCUPIED", "COMING_SOON"]).default("AVAILABLE"),
  contactPhone: z.string().min(9),
  whatsappNumber: z.string().optional().nullable(),
  universityId: z.string().optional().nullable(),
  imageUrls: z.array(z.string()).default([]),
});

export const internshipSchema = z.object({
  title: z.string().min(5),
  companyName: z.string().min(2),
  location: z.string().min(2),
  category: z.enum([
    "TECHNOLOGY",
    "FINANCE",
    "MARKETING",
    "ENGINEERING",
    "HEALTHCARE",
    "EDUCATION",
    "HOSPITALITY",
    "AGRICULTURE",
    "MEDIA",
    "OTHER",
  ]),
  duration: z.string().min(2),
  requirements: z.string().min(20),
  description: z.string().min(30),
  applicationDeadline: z.string(),
  applicationInstructions: z.string().min(10),
  stipend: z.string().optional().nullable(),
  paid: z.boolean().default(false),
  workMode: z.enum(["REMOTE", "ONSITE", "HYBRID"]).default("ONSITE"),
  contactEmail: z.string().email().optional().nullable(),
  contactPhone: z.string().optional().nullable(),
});
